# Load ds

In [1]:
import pandas as pd

In [2]:
ds = pd.read_csv('../data/Cleaned_ds.csv')

In [3]:
ds.head()

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,...,population_density,location,income_level,price,price_rounded,base_price,amenities_score,distance_penalty,crime_penalty,price_realistic
0,1360,6,2,2,9,10,0,0,1,0,...,7242,premium,low,5.952493e+05,595249,12240000,100000,200000,347000.0,11793000.0
1,4272,5,2,3,24,8,1,0,0,1,...,7729,low,low,1.571208e+06,1571208,12816000,200000,160000,20000.0,12836000.0
2,3592,1,4,3,4,20,0,1,1,1,...,1081,premium,mid,1.379943e+06,1379943,32328000,300000,400000,314500.0,31913500.0
3,966,5,2,2,6,14,1,0,0,0,...,8912,medium,low,4.367819e+05,436782,5796000,100000,280000,448000.0,5168000.0
4,4926,4,3,1,18,9,0,0,0,0,...,8146,low,mid,1.792425e+06,1792425,14778000,0,180000,142000.0,14456000.0

In [4]:
ds.columns

Index(['area', 'bedrooms', 'bathrooms', 'floors', 'age', 'distance', 'garage',
       'parking', 'garden', 'security', 'school_nearby', 'hospital_nearby',
       'shopping_mall_nearby', 'public_transport', 'crime_rate',
       'population_density', 'location', 'income_level', 'price',
       'price_rounded', 'base_price', 'amenities_score', 'distance_penalty',
       'crime_penalty', 'price_realistic'],
      dtype='object')

In [5]:
ds.shape

(50000, 25)

# Variables
Needed for traning

**Input Features**

In [6]:
 ds[['area', 'bedrooms', 'bathrooms', 'floors',
 'distance', 'population_density',
 'amenities_score', 'crime_penalty']].head()

,area,bedrooms,bathrooms,floors,distance,population_density,amenities_score,crime_penalty
0,1360,6,2,2,10,7242,100000,347000.0
1,4272,5,2,3,8,7729,200000,20000.0
2,3592,1,4,3,20,1081,300000,314500.0
3,966,5,2,2,14,8912,100000,448000.0
4,4926,4,3,1,9,8146,0,142000.0

In [7]:
X = ds[['area', 'bedrooms', 'bathrooms', 'floors',
 'distance', 'population_density',
 'amenities_score', 'crime_penalty']]

**Target**

In [8]:
y = ds['price_realistic']

## Train

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 42)

## Linear Regression

In [11]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = lr.predict(X_test)

In [13]:
y_pred

array([10707682.53292293,  4822058.51913422, 26991274.62072971, ...,
       17157523.00603766, 17438073.89947508, 27915485.88433069],
      shape=(10000,))

In [14]:
y

0        11793000.0
1        12836000.0
2        31913500.0
3         5168000.0
4        14456000.0
            ...
49995     6152000.0
49996     9827500.0
49997    12955000.0
49998     8311000.0
49999    33715500.0
Name: price_realistic, Length: 50000, dtype: float64

**Model Evaluation Metrics**

In [15]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

In [16]:
mae

5545596.6945469

**RMSE – Root Mean Squared Error**

In [17]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 7485950.395491002

**R² Score**

In [18]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

In [19]:
r2

0.5213512999207381

# Improved-Version

## IP Features

In [20]:
ds.columns

Index(['area', 'bedrooms', 'bathrooms', 'floors', 'age', 'distance', 'garage',
       'parking', 'garden', 'security', 'school_nearby', 'hospital_nearby',
       'shopping_mall_nearby', 'public_transport', 'crime_rate',
       'population_density', 'location', 'income_level', 'price',
       'price_rounded', 'base_price', 'amenities_score', 'distance_penalty',
       'crime_penalty', 'price_realistic'],
      dtype='object')

In [21]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   area                  50000 non-null  int64
 1   bedrooms              50000 non-null  int64
 2   bathrooms             50000 non-null  int64
 3   floors                50000 non-null  int64
 4   age                   50000 non-null  int64
 5   distance              50000 non-null  int64
 6   garage                50000 non-null  int64
 7   parking               50000 non-null  int64
 8   garden                50000 non-null  int64
 9   security              50000 non-null  int64
 10  school_nearby         50000 non-null  int64
 11  hospital_nearby       50000 non-null  int64
 12  shopping_mall_nearby  50000 non-null  int64
 13  public_transport      50000 non-null  int64
 14  crime_rate            50000 non-null  float64
 15  population_density    50000 non-null  int64
 16  location              50000 non-null  object
 17  income_level          50000 non-null  object
 18  price                 50000 non-null  float64
 19  price_rounded         50000 non-null  int64
 20  base_price            50000 non-null  int64
 21  amenities_score       50000 non-null  int64
 22  distance_penalty      50000 non-null  int64
 23  crime_penalty         50000 non-null  float64
 24  price_realistic       50000 non-null  float64
dtypes: float64(4), int64(19), object(2)
memory usage: 9.5+ MB

In [22]:

numerical_cols = ds.select_dtypes(include=['int64', 'float64']).columns.tolist()

binary_cols = [col for col in numerical_cols if ds[col].nunique() == 2]

categorical_cols = ds.select_dtypes(include=['object']).columns.tolist()

In [23]:
numerical_cols

['area',
 'bedrooms',
 'bathrooms',
 'floors',
 'age',
 'distance',
 'garage',
 'parking',
 'garden',
 'security',
 'school_nearby',
 'hospital_nearby',
 'shopping_mall_nearby',
 'public_transport',
 'crime_rate',
 'population_density',
 'price',
 'price_rounded',
 'base_price',
 'amenities_score',
 'distance_penalty',
 'crime_penalty',
 'price_realistic']

In [24]:
binary_cols

['garage',
 'parking',
 'garden',
 'security',
 'school_nearby',
 'hospital_nearby',
 'shopping_mall_nearby',
 'public_transport']

In [25]:
categorical_cols

['location', 'income_level']

In [26]:
X = ds[[
    'area',
    'bedrooms',
    'bathrooms',
    'floors',
    'age',
    'distance',
    'garage',
    'parking',
    'garden',
    'security',
    'school_nearby',
    'hospital_nearby',
    'shopping_mall_nearby',
    'public_transport',
    'crime_rate',
    'population_density',
    'location',
    'income_level'
]]

In [27]:
y = ds['price_realistic']

In [28]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [29]:
X

,area,bedrooms,bathrooms,floors,age,distance,garage,parking,garden,security,school_nearby,hospital_nearby,shopping_mall_nearby,public_transport,crime_rate,population_density,location_medium,location_premium,income_level_low,income_level_mid
0,1360,6,2,2,9,10,0,0,1,0,1,0,1,0,6.94,7242,0,1,1,0
1,4272,5,2,3,24,8,1,0,0,1,1,1,1,0,0.40,7729,0,0,1,0
2,3592,1,4,3,4,20,0,1,1,1,0,1,0,1,6.29,1081,0,1,0,1
3,966,5,2,2,6,14,1,0,0,0,0,1,1,0,8.96,8912,1,0,1,0
4,4926,4,3,1,18,9,0,0,0,0,1,0,1,1,2.84,8146,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,733,1,4,1,23,23,0,0,1,0,0,1,1,1,1.70,2188,0,1,0,1
49996,3420,4,1,3,9,13,1,1,1,0,0,0,1,1,9.45,7273,0,0,1,0
49997,2218,3,1,2,3,6,0,1,1,0,1,0,0,1,8.66,9856,1,0,0,1
49998,992,2,4,3,26,20,1,0,0,0,0,0,1,0,6.34,2858,0,1,1,0
49999,3782,1,2,2,5,13,1,0,0,1,1,1,0,0,5.25,8465,0,1,0,0

## Training

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 42)

## Linear Regression

In [32]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [33]:
y_pred = lr.predict(X_test)

In [34]:
y_pred

array([10684563.91643092, 13134884.04302386, 27040359.61520045, ...,
        8831752.78354926, 17489775.97780146, 36221147.28192054],
      shape=(10000,))

In [35]:
y

0        11793000.0
1        12836000.0
2        31913500.0
3         5168000.0
4        14456000.0
            ...
49995     6152000.0
49996     9827500.0
49997    12955000.0
49998     8311000.0
49999    33715500.0
Name: price_realistic, Length: 50000, dtype: float64

## Evalution

In [36]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

In [37]:
mae

2260258.857804

In [38]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 3184755.494477791

In [39]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

In [40]:
r2

0.913368629513663

# Testing

**Example 1: Premium Urban House**

In [41]:
test_house = {
    'area': 3800,                 # sq ft
    'bedrooms': 5,
    'bathrooms': 7,
    'floors': 2,
    'age': 5,                     # years
    'distance': 4,                # km from city
    'garage': 1,
    'parking': 1,
    'garden': 1,
    'security': 1,
    'school_nearby': 1,
    'hospital_nearby': 1,
    'shopping_mall_nearby': 1,
    'public_transport': 1,
    'crime_rate': 2.5,            # low crime
    'population_density': 8500,
    'location': 'premium',
    'income_level': 'high'
}

In [42]:
test_df = pd.DataFrame([test_house])

In [43]:
test_df = pd.get_dummies(test_df, drop_first=True, dtype=int)

In [44]:
test_df = test_df.reindex(columns=X.columns, fill_value=0)

In [45]:
predicted_price = lr.predict(test_df)
price = predicted_price[0]

print(f"Predicted Price: ₹{price:,.0f}")

Predicted Price: ₹14,869,208

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)